version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network
volumes:
  db-data:
networks:
  laravel-network: